[workspace]
resolver = "2"
members = [
    "crates/ts-core",
    "crates/ts-format",
    "crates/ts-store",
    "crates/ts-p2p",
    "crates/ts-proxy",
    "crates/ts-cli",
]
exclude = ["fuzz"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
thiserror = "2"
serde_cbor = "0.11"
